<? 
$orderXls = array( 
 array( '받는분이름','nameReceiver','받는분 이름 표시','checked'), 
 array( '우편번호','zipcode','우편번호 표시','checked'), 
 array( '주소','address_','주소 표시 (도로명주소 우선 표시)','checked'), 
 array( '받는분핸드폰','mobileReceiver','받는분 핸드폰번호 표시','checked'), 
 array( '받는분전화번호','phoneReceiver','받는분 전화번호 표시','checked'), 
 array( '상품명','goodsnm','2개이상인경우 외 갯수로 표시됨','checked'), 
 array( '배송메세지','order_memo','배송메세지 표시','checked'), 
 array( '착불여부','deli_type','착불여부표시','checked'), 
 array( '번호','no','순번 표시','checked'), 
 array( '송장번호','deliverycode','송장번호표시','checked'), 
 array( '주문번호','ordno','주문번호 표시',''), 
 array( '주문자명','nameOrder','주문자명 표시',''), 
 array( '주문자전화번호','phoneOrder','주문자 전화번호 표시',''), 
 array( '주문자핸드폰','mobileOrder','주문자 핸드폰 표시',''), 
 array( '주문자아이디','m_id','주문자아이디 표시',''), 
 array( '이메일','email','이메일 표시',''), 
 array( '(구)지번주소','address','(구)지번주소 표시',''), 
 array( '(신)도로명주소','road_address','(신)도로명주소 표시',''), 
 array( '결제수단','settlekind','결제방법 표시',''), 
 array( '결제금액','settleprice','결제금액 표시',''), 
 array( '주문일자','orddt','주문한 일자를 표시 예)2007-10-10',''), 
 array( '주문상태','step','주문상태 표시',''), 
 array( '배송코드','deliveryno','배송사코드표시',''), 
 array( '배송일','ddt','배송일자 표시 예)2007-10-10 18:00:00',''), 
 array( '어바웃쿠폰','about_dc_sum','어바웃쿠폰할인금액',''), 
 array( '배송완료일','confirmdt','배송완료일자 표시 예)2011-11-30 10:00:00',''), 
 array( '입금자','bankSender','입금자명 표시','')); 
$orderGoodsXls = array( 
 array( '번호','no','순번 표시',''), 
 array( '일련번호','sno','주문상품의 일련번호',''), 
 array( '주문번호','ordno','주문번호 표시',''), 
 array( '주문자명','nameOrder','주문자명 표시',''), 
 array( '주문자아이디','m_id','주문자아이디 표시',''), 
 array( '이메일','email','이메일 표시',''), 
 array( '주문자전화번호','phoneOrder','주문자 전화번호 표시',''), 
 array( '주문자핸드폰','mobileOrder','주문자 핸드폰 표시',''), 
 array( '받는분이름','nameReceiver','받는분 이름 표시','checked'), 
 array( '우편번호','zipcode_','우편번호 표시(새 우편번호 우선 표시)','checked'), 
 array( '주소','address_','주소 표시 (도로명주소 우선 표시)','checked'), 
 array( '받는분전화번호','phoneReceiver','받는분 전화번호 표시','checked'), 
 array( '받는분핸드폰','mobileReceiver','받는분 핸드폰번호 표시','checked'), 
 array( '상품명','goodsnm','주문 상품명 표시','checked'), 
 array( '옵션','opt','주문 상품옵션 표시','checked'), 
 array( '수량','ea','주문 상품 수량 표시','checked'), 
 array( '배송메세지','order_memo','배송메세지 표시','checked'), 
 array( '(구)우편번호','zipcode','하이픈(-) 를 포함한 7자리의 우편번호 표시',''), 
 array( '(새)우편번호','zonecode','5자리의 새 우편번호(국가기초구역번호) 표시',''), 
 array( '(구)지번주소','address','(구)지번주소 표시',''), 
 array( '(신)도로명주소','road_address','(신)도로명주소 표시',''), 
 array( '결제수단','settlekind','결제방법 표시',''), 
 array( '주문일자','orddt','주문한 일자를 표시 예)2007-10-10',''), 
 array( '주문상태','step','주문상태 표시',''), 
 array( '상품코드','goodscd','주문 상품코드 표시',''), 
 array( '제조사','maker','주문 상품 제조사 표시',''), 
 array( '원산지','origin','주문 상품 원산지 표시',''), 
 array( '브랜드','brandnm','주문 상품 브랜드 표시',''), 
 array( '매입가','supply','주문 상품 매입가 표시',''), 
 array( '상품가격','price','주문 상품가격 표시',''), 
 array( '결제가격','sprice','주문 상품 결제가격 표시',''), 
 array( '어바웃쿠폰할인단가','about_dc_price','어바웃쿠폰할인단가',''), 
 array( '배송코드','deliveryno','배송사표시',''), 
 array( '송장번호','deliverycode','송장번호표시',''), 
 array( '착불여부','deli_type','착불여부표시','checked'), 
 array( '배송일','ddt','배송일자 표시 예)2007-10-10 18:00:00',''), 
 array( '배송완료일','confirmdt','배송완료일자 표시 예)2011-11-30 10:00:00',''), 
 array( '입금자','bankSender','입금자명 표시','')); 
?>